parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Doctrine\DBAL\Connection:
        factory: ['App\Infrastructure\Persistence\Dbal\ConnectionFactory', 'create']
        arguments:
            - '%env(resolve:DATABASE_URL)%'

    SolidFrame\EventSourcing\Store\EventStoreInterface:
        class: SolidFrame\Symfony\EventSourcing\DbalEventStore
        arguments:
            $connection: '@Doctrine\DBAL\Connection'
            $table: 'event_store'

    SolidFrame\EventSourcing\Snapshot\SnapshotStoreInterface:
        class: SolidFrame\Symfony\EventSourcing\DbalSnapshotStore
        arguments:
            $connection: '@Doctrine\DBAL\Connection'
            $table: 'snapshot_store'

    SolidFrame\EventSourcing\Snapshot\SnapshotAggregateRootRepository:
        arguments:
            $aggregateClass: 'App\Domain\Account\Account'
            $eventStore: '@SolidFrame\EventSourcing\Store\EventStoreInterface'
            $snapshotStore: '@SolidFrame\EventSourcing\Snapshot\SnapshotStoreInterface'

    App\Domain\Account\Port\AccountRepository:
        alias: App\Infrastructure\Persistence\EventSourcedAccountRepository
