parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Modules/*/Domain/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Doctrine\DBAL\Connection:
        factory: ['App\Infrastructure\Persistence\Dbal\ConnectionFactory', 'create']
        arguments:
            - '%env(resolve:DATABASE_URL)%'

    App\Modules\Order\Domain\Port\OrderRepository:
        alias: App\Modules\Order\Infrastructure\Persistence\Dbal\DbalOrderRepository

    App\Modules\Inventory\Domain\Port\ProductRepository:
        alias: App\Modules\Inventory\Infrastructure\Persistence\Dbal\DbalProductRepository

    App\Modules\Payment\Domain\Port\PaymentRepository:
        alias: App\Modules\Payment\Infrastructure\Persistence\Dbal\DbalPaymentRepository
